### ISSUE TITLE
diagrams and SRS

### ISSUE THREAD

**Issue by AmmarahCassim** [AmmarahCassim/FullStackSolutionsCapstoneProject#3]

**Comment by AmmarahCassim** [comment]
![UseCase.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa6134f28b4bc0013daf46c/125516c66e82c728ace21e0d46dd879f008390accda5fd53b652fa912a5265296b51a22a26d4b070ed112e030b0a4eac41590e41fbab887ea5a42062c80d55b98e30063e937f03a6aa8317b500bf228a4e86bebe834ac2e13437aa.jpg)

**Comment by Tcoco4** [comment]
Domai Model done

**Comment by Tcoco4** [comment]
![Package diagram.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa61af5cf1ec1001304bfbd/125516c66e82c728ace21e0d46d89599288384accfedb642a34ff1996b0a65633b0ba92e7391a172fd177a00595e4da4435b5a16a8ac892ba6b76d758d0e0ab8d27f4366846c4ff8e7df46f554f832815d84beb68b49c2e93c21e3888f493c17010ac4.jpg)

**Comment by Tcoco4** [comment]
![Domain Model.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa61af5cf1ec1001304bfbd/125516c66e82c728ace21e0d46cc9b97228b8de9a2e6bb46a81fbcd6395428792c07b7692ac7b629be142a52575d4da9130c0a44fcf9887aa3b16e71df5f19f1c32f0e2a92624cf5f2d75dad0ba821834584b3be8b4dc4ec3e21e088874e2c53.jpg)
